### PR TITLE
Guide to get Linux running on ArtyA7

### PR DESCRIPTION
**Pull request by sebastien-riou**
README updated + some shortcuts in makefiles

WARNING: it took 6 minutes to boot, did I screw up something ?

### CODE REVIEW

**Comment by Dolu1990** [comment]
Hi,
6 mn XD ? How did you booted ?
Normaly that's about 5-10 seconds

**Comment by roman3017** [comment]
For some reason I have also seen drastic SD slow down in the past few weeks. I use spi-max-frequency=25000000 in DTS. But it could be my board issue.

**Comment by sebastien-riou** [comment]
spi-max-frequency=25000000 fixed the problem on my side. now boot time is few seconds.

**Comment by Dolu1990** [comment]
I also fixed it, no need to add spi-max-frequency, as it is by default F/2. That's pushed

**Comment by Dolu1990** [comment]
Thanks ^^

**Pull request merged**
