### PR TITLE
Update BSP for NexysA7

### PR DESCRIPTION
**Pull request by roman3017**

### CODE REVIEW

**Comment by Dolu1990** [comment]
About the BSP, i'm still trying to figure out what would be the best structure XD
If you have any idea how to improve let's me know ^^

**Comment by roman3017** [comment]
Maybe SBI and patches for uboot/linux/buildroot can be moved to common and only dts/defconfig files should be kept in separate BSPs to reduce code duplication?

**Comment by Dolu1990** [comment]
Yes, there could be a set of default/common things. That's fine as long we still allow fully custom configs.

Hoo about linux, got 5.10rc3 to boot and run to the shell :)
There was a bug in vex, and again, i have much localy not pushed yet.

**Comment by roman3017** [comment]
Linux 5.10 is really good news, I am looking forward to it. Keeping code close to upstream will make sure we do not diverge much before we push it upstream.

**Pull request merged**
