### PR TITLE
Update memory layout for miniSpartan+

### PR DESCRIPTION
**Pull request by roman3017**
- memory layout for booting using u-boot-spl falcon mode
 - readme instructions

### CODE REVIEW

**Comment by Dolu1990** [comment]
I'm also working on getting multi core linux in + maybe allowing the BMB to be also used for peripherals, without overhead :)

**Comment by roman3017** [comment]
@Dolu1990 I am looking forward to try multi core Linux. Currently I am tying up loose ends of booting using u-boot-spl in falcon mode. I use it on Scarab's miniSpartan+, Anlogic's Tang and Digilent's NexysA7. Once done, I will try multi core Linux and also update Linux to latest. Is there a plan to upstream SaxonSoc u-boot and Linux?

**Comment by Dolu1990** [comment]
@roman3017 So about linux update, a fiew things. I will remove the machineModeSbi.bin to get opensbi instead. Then about Linux 5.1+, i think that's too early to go in it, as the RISC-v 32  bits toolchain lag behind, and is still stuck to 5.0, due to 2038 stuff.  (see https://github.com/riscv/riscv-gnu-toolchain linux-headers version)

Then about upstreaming the things, honnetly, no real plans for that, but anyway, i will have to clean the changes i made in the linux repo / Buildroot repo to get something cleaner and without all those branches XD

**Comment by roman3017** [comment]
@Dolu1990 Oh, the toolchain. You are right, forgot about that. Once there is an upstreaming plan, please let me know if you need my help to upstream my u-boot changes.

**Pull request merged**
