### PR TITLE
Adding support for Xyloni PCB

### PR DESCRIPTION
**Pull request by surabibio**
Added Xyloni PCB for SaxonSoc. The scala code is in a flat format. I found great difficulty in understanding the flow of Abstract Classes and Objects. Most hardware engineers I believe will feel the same. Hence a new flat format and I hope you will accept it.

### CODE REVIEW

**Comment by Dolu1990** [comment]
Hi,

>  I found great difficulty in understanding the flow of Abstract Classes and Objects. Most hardware engineers I believe will feel the same. 

Yes i understand, the SaxonSoc was quite experimental for a long time, and had quite a few paradigme shift on the flight. So, it is far from being perfect / clean XD

At the end, the main thing emerging out of it is the fiber framework (Handle / hardFork) : 
https://spinalhdl.github.io/SpinalDoc-RTD/master/SpinalHDL/Libraries/fiber.html?highlight=fork

About the PR itself, from which branch did you developed it ? master ? not dev-0.3 ?

Also it seems the PR contains some of the SBT / Scala compilation files ?

**Comment by surabibio** [comment]
Hi Charles,

Thankyou for your mail. You are doing a great job and without SpinalHdl we would have been broke by now.

We ported over 17 years of AHDL code on a Cyclone FPGA to SpinalHdl in an  Effinix Trion FPGA in 3 months. We shipped 6 units so far and I am very grateful to you.

Your work is a life time achievement inspiration.

 

I developed from dev-0.3. I can confirm it works great and we have field tested code.

The PR is incomplete and you can ignore it for now. There are a few more functionalities that I want to add.

 

I will submit a clean and complete PR in the days to come.

Thanks once again for your attention.

 

Ravi

**Comment by Dolu1990** [comment]
> Your work is a life time achievement inspiration.

Thanks :)

> I developed from dev-0.3. I can confirm it works great and we have field tested code.

Ahh, then,don't forget to select dev-0.3 branch as destination branch for the PR.
This PR is currently targeting master branch, which is years behind dev-0.3

> I will submit a clean and complete PR in the days to come.

Ok :D

Regards
Charles

**Comment by surabibio** [comment]
Hi Charles,

I have submitted a new PR with video walkthrough.

Please consider the PR,

BR,

Ravi Ganesh

**Comment by surabibio** [comment]
Hi,

Is there any issue with my PR. It is not merged.

Awaiting your feedback.

Ravi Ganesh

 

 

From: ***@***.*** ***@***.***> 
Sent: Tuesday, June 14, 2022 2:43 AM
To: 'SpinalHDL/SaxonSoc' ***@***.***>
Subject: RE: [SpinalHDL/SaxonSoc] Adding support for Xyloni PCB (PR #73)

 

Hi Charles,

I have submitted a new PR with video walkthrough.

Please consider the PR,

BR,

Ravi Ganesh

**Comment by Dolu1990** [comment]
Sorry for the delay, i just sent a message here : 
https://github.com/SpinalHDL/SaxonSoc/pull/74#issuecomment-1158862422

**Pull request closed without merging**
